### ISSUE TITLE
flowdelegatelayout method not called

### ISSUE THREAD

**Issue by annathomasQB** [gleue/TGLStackedViewController#26]
Hi,

Great library first of all :) it looks fantastic.

I was getting issues in ios9 with constraints involved.. so i tried setting flowlayout delegate method.. but strangely that's not getting called?..

I tried setting it in both the inherited class as well as in TGLStackedViewController.. but both approaches did not work.. any help would be appreciated.. Thanks !!

**Comment by gleue** [comment]
Which delegate methods exactly were not called?

**Comment by annathomasQB** [comment]
(CGSize) collectionView:(UICollectionView *)collectionView layout:(UICollectionViewLayout *)collectionViewLayout sizeForItemAtIndexPath:(NSIndexPath *)indexPath

**Comment by gleue** [comment]
The method is part of the UICollectionViewDelegateFlowLayout protocol, which is used by the UICollectionViewFlowLayout.

The stacked and exposed layouts in this component are direct UICollectionViewLayout subclasses -- and not UICollectionViewFlowLayout subclasses. That's why the delegate methods are not called. Use property -itemSize to set (a uniform) item size.

Alternatively, you could adjust the layout classes' -prepareLayout methods to call a delegate for an item's size instead of using the property value.

**Comment by annathomasQB** [comment]
Wow.. okay.. didn't check that out. silly me :D 

Thanks @gleue  for the prompt response. :+1:
